"""Constants for the Joyonway Spa RS485 integration."""

DOMAIN = "joyonway"

CONF_HOST = "host"
CONF_PORT = "port"

DEFAULT_HOST = "192.168.1.11"
DEFAULT_PORT = 8899
DEFAULT_SCAN_INTERVAL = 30
READ_DURATION = 3
FLOOD_DURATION_EQUIPMENT = 1
FLOOD_DURATION_SETPOINT = 10
FLOOD_DURATION_FILTRATION = 10
FLOOD_INTERVAL = 0.05
